# version: '2.3'

services:
  web:
    build:
      context: ..
      dockerfile: jumpinchat-deploy/srv/Dockerfile
    image: echo.research.clinic/web
    environment:
      - JWT_SECRET=$JWT_SECRET
      - COOKIE_SECRET=$COOKIE_SECRET
      - SHARED_SECRET=$SHARED_SECRET
      - DEPLOY_LOCATION=local
      - JANUS_HTTP_URI=/janus/http
      - JANUS_HTTPS_URI=/janus/http
      - JANUS_WS_URI=/janus/ws
      - JANUS_WSS_URI=/janus/ws
      - JANUS_CODEC=vp8
      - JANUS_TOKEN_SECRET=$JANUS_TOKEN_SECRET
      - JANUS_SERVER_IDS=janus,janus2
      - JANUS_PLUGINS=janus.plugin.videoroom
      - YT_API_KEY=$YT_API_KEY
      - UPLOAD_BASE_PATH=/data/uploads
      - FILE_TOKEN_SECRET=$FILE_TOKEN_SECRET
      - TURN_URIS=lima.research.clinic
      - GCM_API_KEY=$GCM_API_KEY # key for push notifications
      - STRIPE_SK=$STRIPE_SK
      - STRIPE_WH_KEY=$STRIPE_WH_KEY
      - MONGODB_URI=mongodb://mongodb,mongodbslave/tc?replicaSet=rs0
      - REDIS_URI=redis://redis:6379
      - EMAIL_URL=http://email:3001
    expose:
      - "80"
    volumes:
      - uploads:/data/uploads:z
    depends_on:
      - redis
      - mongodb
      - mongodbslave
      - janus
      - janus2
    logging:
      options:
        max-size: '1m'
    restart: always
  web2:
    image: echo.research.clinic/web
    environment:
      - JWT_SECRET=$JWT_SECRET
      - COOKIE_SECRET=$COOKIE_SECRET
      - SHARED_SECRET=$SHARED_SECRET
      - DEPLOY_LOCATION=local
      - JANUS_HTTP_URI=/janus/http
      - JANUS_HTTPS_URI=/janus/http
      - JANUS_WS_URI=/janus/ws
      - JANUS_WSS_URI=/janus/ws
      - JANUS_CODEC=vp8
      - JANUS_TOKEN_SECRET=$JANUS_TOKEN_SECRET
      - JANUS_SERVER_IDS=janus,janus2
      - JANUS_PLUGINS=janus.plugin.videoroom
      - YT_API_KEY=$YT_API_KEY
      - UPLOAD_BASE_PATH=/data/uploads
      - FILE_TOKEN_SECRET=$FILE_TOKEN_SECRET
      - TURN_URIS=lima.research.clinic
      - GCM_API_KEY=$GCM_API_KEY # key for push notifications
      - STRIPE_SK=$STRIPE_SK
      - STRIPE_WH_KEY=$STRIPE_WH_KEY
      - MONGODB_URI=mongodb://mongodb,mongodbslave/tc?replicaSet=rs0
      - REDIS_URI=redis://redis:6379
      - EMAIL_URL=http://email:3001
    expose:
      - "80"
    volumes:
      - uploads:/data/uploads:z
    depends_on:
      - redis
      - mongodb
      - mongodbslave
      - janus
      - janus2
    logging:
      options:
        max-size: '1m'
    restart: always

  home:
    build:
      context: ..
      dockerfile: jumpinchat-deploy/home/Dockerfile
    image: echo.research.clinic/home
    environment:
      - DEPLOY_LOCATION=local
      - COOKIE_SECRET=$COOKIE_SECRET
      - JWT_SECRET=$JWT_SECRET
      - STRIPE_KEY_PUBLIC=$STRIPE_KEY_PUBLIC
      - MONGODB_URI=mongodb://mongodb,mongodbslave/tc?replicaSet=rs0
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - web
      - web2
    logging:
      options:
        max-size: '1m'
  home2:
    image: echo.research.clinic/home
    environment:
      - DEPLOY_LOCATION=local
      - COOKIE_SECRET=$COOKIE_SECRET
      - JWT_SECRET=$JWT_SECRET
      - STRIPE_KEY_PUBLIC=$STRIPE_KEY_PUBLIC
      - MONGODB_URI=mongodb://mongodb,mongodbslave/tc?replicaSet=rs0
    expose:
      - "3000"
    restart: always
    depends_on:
      - web
      - web2
    logging:
      options:
        max-size: '1m'

  mongodb:
    image: docker.io/library/mongo:4.4
    command: "--replSet rs0"
    # expose:
    #   - "27017"
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db:Z
    logging:
      options:
        max-size: '1m'
    restart: always

  mongodbslave:
    image: docker.io/library/mongo:4.4
    command: "--replSet rs0"
    expose:
      - "27017"
    logging:
      options:
        max-size: '1m'
    restart: always
    volumes:
      - ./data/db2:/data/db:Z

  redis:
    image: docker.io/library/redis
    logging:
      options:
        max-size: '1m'
    restart: always

  nginx:
    build:
      context: ./nginx
      args:
        - ENV
    image: echo.research.clinic/nginx
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - uploads:/data/uploads:z,ro
    logging:
      options:
        max-size: '1m'
    depends_on:
      - web
      - web2
      - home
      - home2
    restart: always

  janus:
    build:
      context: ./janus

    image: echo.research.clinic/janus
    expose:
      - "8088"
      - "8889"
      - "8188"
      - "8989"
      - "7888"
    ports:
      - "20000-20100:20000-20100/udp"
    volumes:
      - ./fullchain.pem:/opt/janus/certs/fullchain.pem:z
      - ./privkey.pem:/opt/janus/certs/privkey.pem:z
    environment:
      - DEBUG_COLORS=false
      - SERVER_NAME=janus
      - ENABLE_EVENTS=true
      - ENABLE_RABBIT_EVENTS=false
      - JANUS_TOKEN_SECRET=$JANUS_TOKEN_SECRET
      - NAT_1_1_IP=192.168.88.197
    logging:
      options:
        max-size: '1m'
    restart: always

  janus2:
    image: echo.research.clinic/janus
    expose:
      - "8088"
      - "8889"
      - "8188"
      - "8989"
      - "7888"
    ports:
      - "20101-20200:20101-20200/udp"
    environment:
      - DEBUG_COLORS=false
      - SERVER_NAME=janus2
      - ENABLE_EVENTS=true
      - ENABLE_RABBIT_EVENTS=false
      - JANUS_TOKEN_SECRET=$JANUS_TOKEN_SECRET
      - NAT_1_1_IP=192.168.88.197
      - RTP_PORT_MIN=20101
      - RTP_PORT_MAX=20200
    logging:
      options:
        max-size: '1m'
    volumes:
      - ./core:/opt/janus/bin/core:z
      - ./fullchain.pem:/opt/janus/certs/fullchain.pem:z
      - ./privkey.pem:/opt/janus/certs/privkey.pem:z
    restart: always
  haproxy:
    build: ./haproxy
    image: echo.research.clinic/haproxy
    depends_on:
      - web
      - web2
    expose:
      - "80"
    logging:
      options:
        max-size: '1m'
    restart: always

  email:
    build: ../jumpinchat-email
    image: echo.research.clinic/jic-email
    expose:
      - "3001"
    environment:
      - PORT=3001
      - SMTP_HOST=$SMTP_HOST
      - SMTP_PORT=$SMTP_PORT
      - SMTP_SECURE=$SMTP_SECURE
      - SMTP_USER=$SMTP_USER
      - SMTP_PASS=$SMTP_PASS
      - SMTP_FROM=$SMTP_FROM
      - SHARED_SECRET=$SHARED_SECRET
    logging:
      options:
        max-size: '1m'
    restart: always

volumes:
  uploads:
